version: "3"

services:
  
  redis:
    image: redis
    ports:
      - "6379"
    networks: 
      - frontend
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
  
  httpd:
    image: httpd
    ports:
      - "8080:80"
    networks:
      - frontend
    deploy: 
      replicas: 10
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
    
  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    environment: 
      - POSTGRES_PASSWORD=mypasswd
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
  
networks:
  frontend: 
  backend: 

volumes:
  postgres-db:
